---
title: "PI and ICI Plots"
output: 
  html_document: 
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load packages
library(data.table)
library(ggplot2)
library(gridExtra)
library(ggExtra)
library(xtable)
library(BBmisc)
```

```{r echo=TRUE, message=FALSE, warning=FALSE, results='asis'}
pfi = readRDS("application_importance_realdata.Rds")
mid = "mse"

# write table function
getImpTable = function(pfi, subset.ind = NULL, learner = "regr.randomForest") {
  if (!is.null(subset.ind))
    pfi = subset(pfi, row.id %nin% subset.ind & replace.id %nin% subset.ind)
  imp = pfi[, lapply(.SD, mean, na.rm = TRUE), .SDcols = c("mse"),
    by = c("features", "learner")]
  imp = split(imp, imp$learner)[[learner]]
  imp$mse = round(imp$mse, 1)
  imp = sortByCol(imp[, -"learner"], "mse", asc = FALSE)
  setColNames(as.data.frame(rbind(imp$mse)), imp$features)
}

# get index for LSTAT > 10 in order to remove those observations
pi.ind = unique(pfi$replace.id[pfi$features == "LSTAT" & pfi$feature.value > 10])
ici = subset(pfi, learner == "regr.randomForest" & features == "LSTAT")
ici.integral = ici[, lapply(.SD, mean, na.rm = TRUE), .SDcols = mid, by = "row.id"]
ici.ind = which(ici.integral[[mid]] <= 0)

# produce tables
imp = getImpTable(pfi)
imp.pi = getImpTable(pfi, pi.ind)
imp.ici = getImpTable(pfi, ici.ind)
tab = rbind(imp, imp.pi, imp.ici)
row.names(tab) = c("(1)", "(2)", "(3)")
xtab = xtable(tab, digits = 1)
align(xtab) = c(rep("c|", length(align(xtab)) - 1), "c")
caption(xtab) = "PFI values calculated for a random forest trained on the Boston housing training set and using the MSE on the test data. The PFI values in row (1) are based on all observations from the test set, in row (2) on a subset where $\\text{LSTAT} < 10$ and in row (3) after removing observations having a negative ICI integral."
label(xtab) = "tab:imp"
print(xtab, include.rownames = TRUE, caption.placement = "top", type = "html")
```

```{r piplot, echo=TRUE, message=FALSE, warning=FALSE, fig.width=7, fig.height=5, fig.cap="PI and ICI plots for a random forest and the two most important features of the Boston housing data (LSTAT and RM). The horizontal lines in the PI plots represent the value of the global PFI (i.e. the integral of the PI curve). Marginal distribution histograms for features and partial importances are added in the PI and ICI plot margins, respectively. The ICI curve with the largest integral is highlighted in green and the curve with the smallest integral in red.", fig.pos="ht"}
plotPartialImportance = function(pfi, feat, learner.id, mid,
  marginal = FALSE, individual = FALSE, rug = TRUE, hline = TRUE, 
  grid.points = TRUE, subset.observation.index = NULL, subset.replaced.index = NULL) {
  d = copy(subset(pfi, learner == learner.id & features == feat))
  d$feature.value = as.numeric(as.character(d$feature.value))
  if (!is.null(subset.observation.index))
    d = subset(d, row.id %in% subset.observation.index)
  if (!is.null(subset.replaced.index))
    d = subset(d, replace.id %in% subset.replaced.index)

  pi = d[, lapply(.SD, mean, na.rm = TRUE),
    .SDcols = c(mid), by = c("replace.id", "features", "learner", "feature.value")]

  pp = ggplot(data = as.data.frame(pi), aes_string(x = "feature.value", y = mid))
  if (grid.points)
    pp = pp + geom_point()
  if (individual) {
    pp = pp + geom_point(shape = NA) + geom_line(data = as.data.frame(na.omit(d)),
      aes_string(x = "feature.value", y = mid, group = "row.id"), color = "gray")
  }
  pp = pp + geom_line(data = as.data.frame(pi), aes_string(x = "feature.value", y = mid))
  if (rug)
    pp = pp + geom_rug()
  if (hline)
    pp = pp + geom_hline(yintercept = mean(pi[[mid]]))
  if (marginal)
    ggMarginal(pp, type = "histogram", fill = "transparent") else
      pp
}

learner.id = "regr.randomForest"
mid = "mse"
features = c("LSTAT", "RM")

pp = lapply(features, function(feat) {
  ici = subset(pfi, learner == learner.id & features == feat)
  ici.integral = ici[, lapply(.SD, mean, na.rm = TRUE), .SDcols = mid, by = "row.id"]
  ind = c(which.min(ici.integral[[mid]]), which.max(ici.integral[[mid]])) # unlist(ind[[feat]])
  ici.obs = subset(ici, row.id %in% ici.integral$row.id[ind])

  # PI plots
  pi.plot = plotPartialImportance(pfi, feat, learner.id, mid, rug = FALSE)
  pi.plot = pi.plot +
      labs(title = "PI plot", y = bquote(Delta~L ~ "based on" ~ .(toupper(mid)))) +
      xlab(feat) +
      theme(legend.position = "none", title = element_text(size = 8), axis.title = element_text(size = 8))
  
  # ICI plots
  ici.plot = plotPartialImportance(pfi, feat, learner.id, mid,
    individual = TRUE, grid.points = FALSE, rug = FALSE, hline = FALSE)
  ici.plot = ici.plot +
    geom_line(data = ici.obs, aes_string(x = "feature.value", y = mid,
      color = "factor(row.id)",
      group = "row.id")) +
    labs(title = "ICI plot", y = bquote(Delta~L ~ "based on" ~ .(toupper(mid)))) +
    xlab(feat) +
    theme(legend.position = "none", title = element_text(size = 8), axis.title = element_text(size = 8))
  
  list(
    pi.plot,
    ici.plot
  )
})
pp = unlist(pp, recursive = FALSE)

pp[c(1,3)] = lapply(pp[c(1,3)], function(p)
  ggMarginal(p, type = "histogram", fill = "transparent"))
pp[c(2,4)] = lapply(pp[c(2,4)], function(p)
  ggMarginal(p, type = "histogram", fill = "transparent", margins = "y"))
do.call(grid.arrange, pp[c(1,3,2,4)])
```

